### ISSUE TITLE
When using the switch -da

### ISSUE THREAD

**Issue by astondevops** [igbt6/Packt-Publishing-Free-Learning#21]
In addition when using the switch -da I've got 
 python3 packtPublishingFreeEbook.py -da
[INFO] - Creating session...
[INFO] - Session created, logged in successfully!
[INFO] - Getting data of all your books...
[INFO] - Opened 'https://www.packtpub.com/account/my-ebooks' successfully!
[ERROR] - Exception occurred 'NoneType' object has no attribute 'find_all'

**Comment by igbt6** [comment]
Hello, looks like your books list is empty ? I have tested the switch -da at the moment and it works well on my ubuntu 16.04 with python 3.5 installed, Does it happen on localhost or also on the docker container you mentioned in the previous post

**Comment by frederikkunze** [comment]
I had this too. I managed to find the issue. For me it was wrong login credentials(wrong password).

**Comment by igbt6** [comment]
already fixed on  master, chek this out!
